{% set name = "tinyarray" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://downloads.kwant-project.org/tinyarray/tinyarray-{{ version }}.tar.gz
  sha256: 9a2f5a98c0dcba1e7c42ccaf0caef382c822349b8038ad31e4f8c9abe4c71c87

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pytest
  run:
    - python

test:
  requires:
    - numpy
    - pytest
  source_files:
    - test_tinyarray.py
  commands:
    - python test_tinyarray.py
  imports:
    - tinyarray

about:
  home: http://git.kwant-project.org/tinyarray/about/
  license: BSD 2-Clause
  license_file: LICENSE.rst
  summary: 'Arrays of numbers for Python, optimized for small sizes'
  description: |
    Tinyarrays are similar to NumPy arrays, but optimized for small sizes.
    Common operations on very small arrays are to 3-7 times faster than
    with NumPy (with NumPy 1.6 it used to be up to 35 times), and 3 times
    less memory is used to store them. Tinyarrays are useful if you need
    many small arrays of numbers, and cannot combine them into a few
    large ones.
  doc_url: https://gitlab.kwant-project.org/kwant/tinyarray

extra:
  recipe-maintainers:
    - basnijholt
