{% set name = "tinyarray" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://gitlab.kwant-project.org/kwant/tinyarray/repository/archive.tar.gz?ref=v{{ version }}
  sha256: 5986fb459eba3ce75af294c285c13a83d0963a58699c85002fc0921dc2bdb996
  
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - pytest
  run:
    - python

test:
  requires:
    - numpy
    - pytest
  source_files:
    - test_tinyarray.py
  commands:
    - python test_tinyarray.py
  imports:
    - tinyarray

about:
  home: http://git.kwant-project.org/tinyarray/about/
  license: BSD 2-Clause
  license_file: LICENSE.rst
  summary: 'Arrays of numbers for Python, optimized for small sizes'
  description: |
    Tinyarrays are similar to NumPy arrays, but optimized for small sizes. 
    Common operations on very small arrays are to 3-7 times faster than 
    with NumPy (with NumPy 1.6 it used to be up to 35 times), and 3 times 
    less memory is used to store them. Tinyarrays are useful if you need 
    many small arrays of numbers, and cannot combine them into a few 
    large ones.
  doc_url: https://gitlab.kwant-project.org/kwant/tinyarray

extra:
  recipe-maintainers:
    - basnijholt
