travis:
  secure:
    BINSTAR_TOKEN: nPdVD/QJQyIibIozU9a43ZtBwCcjz6d0Qapui68hOvdPTc9LGVYK7vYvIRg9cNjtPaOk2b2tSdBwLdpSFlvAolgNlpfxaOPL6AH4gppEBUf3uxdXfGEu8kfwZzpvA3I3nrvImd3RQPlWJID8lJaurEX3T3/r2eL65IfvXPplvvQKd21z6sFRe6JzFTH6egRU4LgVgeKDtaa/7R2fkkRWoWAyEK6xZh9sEIb0OoanVorHHtnet0EptyY73bGye+GnUx4FLLIyCSlhoKmaxz1HK8y5gJSFvqPzmQ6cJj3sdQlvr7+nAZZViUCpOdI3+Wq/mX9IlTQYxts/EaCbH3LLU8HgpUciw7yXf8WSz7zR7cQs92DwlilmzkGEYTM/ganaogVO1TN/HTw5gpO7dFWETqUymRmaZFQfvUvcocZYxiGPo1EGo2xB9depOB05FzsPoiRyPc5Wz+MoGit0BAPGwpBE9dNICyI6CYlYy+JdEc+AHkNnPjmQzgXwlw+vFf+YiGUrGlhNL6xaBlyqwzhynilF/2jZW+WUenjDawX3wU79Iyu+XrWg4lywrkBKhQZ0oS0i1wqR/MwjOpV8W2qD0TmtKY7xe2wQIgUnTCymCvfVWFg0jpBBxpOt7ZAIHEUr1pTqsxOy1ntx2/eAhckU2Fz0rsWA7bGsLBX3eROz/tg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
