travis:
  secure:
    BINSTAR_TOKEN: FxwDlnOeUdHjRNal0fjCwl52KiE09a88EBQ66FAo1Z1d/1HlwUWyJSPNkLAFvv/bhNibPRwSjJ7xhKzENHS1t0LET99tPc3etcdfjwzZ7gtAjFsAmfYRWE2sesI7Hl7OAtd7GvtA2Yo7izDEPCmdIKmJFJzM6FMDGye7i7cXTJHl9I56PIroW5rTNHzP0q5+nnWpg1pxHMprcF7ad9OtYJB0CrfQQWOpISUfVh9sxkkvuhJW7egs0JAjND3hxm+m3XPcD02YifPkCSRzOmJ7w2Lb+6DBYFkM7Pb5MRgNMfFVtIOZMDM+cklVMHh9rAiSQYq7qaAfkRd/wxJg5K5dI+WfPiz51HMjXWyfGjveibLE3IURl+exPQ64AJyyqGEWxyBkiReni9608165+ECVVO8RnfkMEvc3MQyD17KK7H7jGYJjoueb//pvWQrYGp+WzGH8aSFZJNA0gCmWz7y+lemwrVTQlfAukCvY7E0V8sexCk/UkP8BEMW44qx9j2xvS0taFoJeu8XkswISfcXBS/j4zAS5/YW0XnhVcPBZz0qWtxxmxHXnF5i7F5fiFZW0z5EuIu5EoW5hl6+g/UlQsT/sFSTPi9fv1ZYFoK9InfS+W+7/vnZRMv08twaCtmc9msgqult40FjwGJ5yjq4pJMkSmcDZpAPgIP4gj/tZu+w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
